/* =============================================================================
 * firmware_types.h — 固件领域类型
 *
 * 枚举值是原固件输入扫描和状态机之间的既有数值契约。它们只用于局部变量、
 * 函数参数和分支表达式；映射到 SRAM 的状态仍按明确的 uint8_t/uint32_t 访问。
 * ========================================================================== */
#ifndef FIRMWARE_TYPES_H
#define FIRMWARE_TYPES_H

#include <stdint.h>

typedef enum {
  KEY_NONE = 0x00,
  KEY_CONFIRM = 0x01,
  KEY_DOWN = 0x02,
  KEY_UP = 0x03,
  KEY_BACK = 0x04,
  KEY_START = 0x05,
  KEY_STOP = 0x06,
  KEY_SLOW_UP = 0x0B,
  KEY_INITIAL_PARAMETER_PASSWORD = 0x0E,
  KEY_COMBINED_SLOW_DOWN = KEY_INITIAL_PARAMETER_PASSWORD,
  KEY_FAST_UP = 0x16,
  KEY_CLEAR_STATISTICS = 0x17,
  KEY_SLOW_DOWN = KEY_CLEAR_STATISTICS,
  KEY_FAST_DOWN = 0x21
} KeyCode;

typedef enum {
  UI_SCREEN_MAIN_MENU = 1,
  UI_SCREEN_BASIC_PARAMETERS = 2,
  UI_SCREEN_BASIC_PARAMETER_EDIT = 3,
  UI_SCREEN_PROTECTION_PARAMETERS = 4,
  UI_SCREEN_COMMUNICATION_PARAMETERS = 5,
  UI_SCREEN_RUNTIME_HOURS = 6,
  UI_SCREEN_PID_PARAMETERS = 7,
  UI_SCREEN_PHASE_CALIBRATION = 8,
  UI_SCREEN_VERSION = 9,
  UI_SCREEN_CALIBRATION_MENU = 0x0A,
  UI_SCREEN_RUNTIME_QUERY = 0x0B,
  UI_SCREEN_RUNTIME_CLEAR = 0x0C,
  UI_SCREEN_STATUS_MONITOR = 0x14,
  UI_SCREEN_AUTHENTICATION = 0x1E,
  UI_SCREEN_CALIBRATION_ACTIVE = 0x62,
  UI_SCREEN_CALIBRATION_RESULT = 0x63,
  UI_SCREEN_MANUAL_BALANCE = 0x5A
} UiScreenId;

/* 面板控制方式：本地、通讯给定、固定给定。 */
typedef enum {
  CONTROL_MODE_VOLTAGE = 0,
  CONTROL_MODE_CURRENT = 1,
  CONTROL_MODE_OPEN_LOOP = 2
} ControlMode;

typedef enum {
  START_MODE_JOG = 0,
  START_MODE_LATCHED = 1
} StartMode;

typedef enum {
  FEEDBACK_DISABLED = 0,
  FEEDBACK_ENABLED = 1
} FeedbackMode;

typedef enum {
  PARITY_NONE = 0,
  PARITY_ODD = 1,
  PARITY_EVEN = 2,
  PARITY_ONE_STOP_BIT = 3
} ParityMode;

typedef enum {
  RUN_STATE_STOPPED = 0,
  RUN_STATE_STARTING = 1,
  RUN_STATE_RUNNING = 4,
  RUN_STATE_STABLE = 5
} RunState;

typedef enum {
  OUTPUT_STATE_IDLE = 0,
  OUTPUT_STATE_STARTING = 1,
  OUTPUT_STATE_ACTIVE = 4,
  OUTPUT_STATE_STABLE = 5
} OutputState;

typedef enum {
  PARAMETER_SYNC_IDLE = 0,
  PARAMETER_SYNC_PENDING = 1,
  PARAMETER_SYNC_RETRYING = 2
} ParameterSyncState;

typedef enum {
  FAULT_PHASE_A_LOSS = 1u << 0,
  FAULT_PHASE_B_LOSS = 1u << 1,
  FAULT_PHASE_C_LOSS = 1u << 2,
  FAULT_PHASE_IMBALANCE = 1u << 3,
  FAULT_OVERVOLTAGE = 1u << 4,
  FAULT_UNDERVOLTAGE = 1u << 5,
  FAULT_CURRENT_LIMIT = 1u << 6,
  FAULT_EXTERNAL_INPUT = 1u << 7,
  FAULT_FEEDBACK_TIMEOUT = 1u << 8,
  FAULT_SEVERE_PHASE_IMBALANCE = 1u << 9,
  FAULT_OUTPUT_TIMEOUT = 1u << 10,
  FAULT_FEEDBACK_LOSS = 1u << 11,
  FAULT_STARTUP_TIMEOUT = 1u << 12,
  FAULT_EMERGENCY_STOP = 1u << 13,
  FAULT_EXTERNAL_RESET = 1u << 14,
  FAULT_HARDWARE_RESET = 1u << 15
} FaultFlags;

typedef enum {
  MODBUS_READ_HOLDING_REGISTERS = 0x03,
  MODBUS_WRITE_SINGLE_REGISTER = 0x06,
  MODBUS_WRITE_MULTIPLE_REGISTERS = 0x10
} ModbusFunctionCode;

typedef enum {
  REGISTER_READ_ONLY = 1u << 0,
  REGISTER_WRITE_ONLY = 1u << 1,
  REGISTER_READ_WRITE = REGISTER_READ_ONLY | REGISTER_WRITE_ONLY
} ModbusRegisterAccess;

typedef enum {
  PARAMETER_STORAGE_BYTE = 1,
  PARAMETER_STORAGE_WORD = 4
} ParameterStorageWidth;

#endif /* FIRMWARE_TYPES_H */
